# Example Usage - Differential Evolution (DE)

Auto Reload Submodules

In [32]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Import path

In [33]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

Set up logger

In [34]:
import logging

# logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')

logging.basicConfig(
    encoding="utf-8",
    filemode="a",
    format="[{asctime}] [{levelname}] {message}",
    style="{",
    datefmt="%Y-%m-%d, %H:%M",
    level=logging.INFO,
)

logger = logging.getLogger()
# logger.setLevel(logging.DEBUG)
# logger.setLevel(logging.INFO)



In [35]:
logger.info("Hello logging!")

[2025-06-29, 22:31] [INFO] Hello logging!


Now, we can define a set of Genes using:

In [36]:
from pyeas._population import Genes

Genes(bounds=(-1,2), number=10)

Genes(bounds=(-1, 2), number=10)

Next, we define the structure of a 'genome' or member my making a list of genes:

In [37]:
member = [
    Genes(bounds=(-1,0), number=2),
    Genes(bounds=(4,8), number=1),
    Genes(bounds=(0,1), number=2),
]

In [38]:
from pyeas._population import Population


pop = Population(
    size=3,
    member=member,
)

[2025-06-29, 22:31] [INFO] [Population] Each Member has 5 genes
[2025-06-29, 22:31] [INFO] [Population] Gene members: N=2 ∈(-1, 0), N=1 ∈(4, 8), N=2 ∈(0, 1)
[2025-06-29, 22:31] [INFO] [Population] Population size (number of members) is 3


Genes(bounds=(-1, 0), number=2)
Genes(bounds=(4, 8), number=1)
Genes(bounds=(0, 1), number=2)


In [39]:
pop.population_raw

array([[0.06434, 0.45831, 0.07177, 0.53152, 0.08946],
       [0.1042 , 0.57587, 0.73779, 0.68754, 0.33528],
       [0.20778, 0.61367, 0.25333, 0.83429, 0.21747]])

In [40]:
pop.groupings

array([2, 1, 2])

In [41]:
pop.bounds

array([[-1,  0],
       [-1,  0],
       [ 4,  8],
       [ 0,  1],
       [ 0,  1]])

In [ ]:
pop.population_raw

array([[0.57378, 0.50095, 0.93521, 0.9265 , 0.34824],
       [0.95953, 0.04195, 0.5288 , 0.39586, 0.78417],
       [0.71087, 0.71607, 0.78821, 0.60411, 0.32253]])

In [ ]:
a = pop.denormalise(pop.population_raw)

a

array([[-0.42622, -0.49905,  7.74084,  0.9265 ,  0.34824],
       [-0.04047, -0.95805,  6.1152 ,  0.39586,  0.78417],
       [-0.28913, -0.28393,  7.15284,  0.60411,  0.32253]])

In [ ]:
pop.normalise(a)

array([[0.57378, 0.50095, 0.93521, 0.9265 , 0.34824],
       [0.95953, 0.04195, 0.5288 , 0.39586, 0.78417],
       [0.71087, 0.71607, 0.78821, 0.60411, 0.32253]])

In [ ]:
d = pop.group(
    pop.denormalise(pop.population_raw)
)
d

array([[array([-0.42622, -0.49905]), array([7.74084]),
        array([0.9265 , 0.34824])],
       [array([-0.04047, -0.95805]), array([6.1152]),
        array([0.39586, 0.78417])],
       [array([-0.28913, -0.28393]), array([7.15284]),
        array([0.60411, 0.32253])]], dtype=object)

In [21]:
import numpy as np 
np.shape(d)

(3, 3)

In [28]:
np.concat(d, axis=0)

array([array([-0.42622, -0.49905]), array([7.74084]),
       array([0.9265 , 0.34824]), array([-0.04047, -0.95805]),
       array([6.1152]), array([0.39586, 0.78417]),
       array([-0.28913, -0.28393]), array([7.15284]),
       array([0.60411, 0.32253])], dtype=object)

In [ ]:
pop.ungroup(d)

array([[-0.42622, -0.49905,  7.74084,  0.9265 ,  0.34824],
       [-0.04047, -0.95805,  6.1152 ,  0.39586,  0.78417],
       [-0.28913, -0.28393,  7.15284,  0.60411,  0.32253]])

In [ ]:
pop.normalise(
    pop.ungroup(d)
)


array([[0.57378, 0.50095, 0.93521, 0.9265 , 0.34824],
       [0.95953, 0.04195, 0.5288 , 0.39586, 0.78417],
       [0.71087, 0.71607, 0.78821, 0.60411, 0.32253]])