# Example Usage - Differential Evolution (DE)

Auto Reload Submodules

In [1]:
%load_ext autoreload
%autoreload 2

Import path

In [2]:
import sys
import os
import numpy as np

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

Set up logger

In [3]:
import logging

logging.basicConfig(
    encoding="utf-8",
    filemode="a",
    format="[{asctime}] [{levelname}] {message}",
    style="{",
    datefmt="%Y-%m-%d, %H:%M",
    level=logging.INFO,
)

logger = logging.getLogger()
logger.info("Hello logging!")

[2025-07-09, 22:19] [INFO] Hello logging!


Now, we can define a set of Genes using:

In [4]:
from pyeas._population import Genes

Genes(bounds=(-1,2), number=10)

Genes(bounds=(-1, 2), number=10)

Next, we define the structure of a 'genome' or member my making a list of genes:

In [5]:
member = [
    Genes(bounds=(-1,0), number=2),
    Genes(bounds=(4,8), number=1),
    Genes(bounds=(0,1), number=2),
]

Then, initialise  the population:

In [22]:
from pyeas._population import Population

pop = Population(
    size=3,
    member=member,
    seed=42,
)

[2025-07-09, 22:27] [INFO] [Population] Each Member has 5 genes


[2025-07-09, 22:27] [INFO] [Population] Gene members: N=2 ∈(-1, 0), N=1 ∈(4, 8), N=2 ∈(0, 1)
[2025-07-09, 22:27] [INFO] [Population] Population size (number of members) is 3


The generated population is:

In [23]:
print(np.shape(pop.population))
pop.population

(3, 5)


array([[-0.22604, -0.56112,  7.4344 ,  0.69737,  0.09418],
       [-0.02438, -0.23886,  7.14424,  0.12811,  0.45039],
       [-0.6292 , -0.07324,  6.57548,  0.82276,  0.44341]])

Now, the raw population is normalised to between zero and one:

In [24]:
print(np.shape(pop.population_raw))
pop.population_raw

(3, 5)


array([[0.77396, 0.43888, 0.8586 , 0.69737, 0.09418],
       [0.97562, 0.76114, 0.78606, 0.12811, 0.45039],
       [0.3708 , 0.92676, 0.64387, 0.82276, 0.44341]])

This is scaled using the bounds:

In [25]:
pop.bounds

array([[-1,  0],
       [-1,  0],
       [ 4,  8],
       [ 0,  1],
       [ 0,  1]])

Finally, we can try and set a new population, we catch this setter and ensure several checks are run:

In [27]:
pop.population = [[1,2], [4,5,6]]

TypeError: Must set the population using an array, not a <class 'list'>

In [31]:
pop.population = np.array([[-0.22604, -0.56112,  7.4344 ,  0.69737,  0.09418,  0.09418],
       [-0.02438, -0.23886,  7.14424,  0.12811,  0.45039,  0.09418],
       [-0.6292 , -0.07324,  6.57548,  0.82276,  0.44341,  0.09418]])

ValueError: Array to set as population must have 5 genes per row, but is shape: (3, 6)

If we exceed the limits (i.e., 0 & 1 for the normalised population) of the bounds, the values are clipped with logging warnings:

In [32]:
pop.population = pop.population*1.8
pop.population

[2025-07-09, 22:34] [WARNING] [Population] [Setter] Normalised population to set contains values below 0! Clipping...
[2025-07-09, 22:34] [WARNING] [Population] [Setter] Normalised population to set contains values above 1! Clipping...
[2025-07-09, 22:34] [INFO] [Population] [Setter] Finished setting population!


array([[-0.40687, -1.     ,  8.     ,  1.     ,  0.16952],
       [-0.04388, -0.42995,  8.     ,  0.2306 ,  0.8107 ],
       [-1.     , -0.13183,  8.     ,  1.     ,  0.79814]])

Next, consider the same population but with the genes remained in a grouping structure (i.e., not flattened):

In [17]:
pop_grouped = Population(
    size=3,
    member=member,
    seed=42,
    flatten_gene_groupings=False,
)

[2025-07-09, 22:26] [INFO] [Population] Members grouped in: [2, 1, 2]
[2025-07-09, 22:26] [INFO] [Population] Each Member has 5 genes
[2025-07-09, 22:26] [INFO] [Population] Gene members: N=2 ∈(-1, 0), N=1 ∈(4, 8), N=2 ∈(0, 1)
[2025-07-09, 22:26] [INFO] [Population] Population size (number of members) is 3


In [18]:
print(np.shape(pop_grouped.population))
pop_grouped.population

(3, 3)


array([[array([-0.22604, -0.56112]), array([7.4344]),
        array([0.69737, 0.09418])],
       [array([-0.02438, -0.23886]), array([7.14424]),
        array([0.12811, 0.45039])],
       [array([-0.6292 , -0.07324]), array([6.57548]),
        array([0.82276, 0.44341])]], dtype=object)

In [54]:
pop_grouped.population

array([[array([-0.22604, -0.56112]), array([7.4344]),
        array([0.69737, 0.09418])],
       [array([-0.02438, -0.23886]), array([7.14424]),
        array([0.12811, 0.45039])],
       [array([-0.6292 , -0.07324]), array([6.57548]),
        array([0.82276, 0.44341])]], dtype=object)

We can similarly assign (and catch) setting to a new population value:

In [63]:
pop_grouped.population = np.array(
    [
        [np.array([-0.22604, -0.56112]), np.array([7.4344]), np.array([0.69737, 0.09418])],
        [np.array([-0.02438, -0.23886]), np.array([7.14424]),np.array([0.12811, 0.45039])],
        [np.array([-0.6292 , -0.07324]), np.array([6.57548]),np.array([0.82276, 0.44341])], 
        [np.array([-0.6292 , -0.07324]), np.array([6.57548]),np.array([0.82276, 0.44341])]
    ],
    dtype=object,
)

ValueError: Array to set as population must have 3 rows, but is shape: (4, 3)

In [ ]:
pop_grouped.population = np.array(
    [
        [np.array([-0.22604, -0.56112]), np.array([7.4344]), np.array([0.69737, 0.09418])],
        [np.array([-0.02438, -0.23886]), np.array([7.14424]),np.array([0.12811, 0.45039])],
        [np.array([-0.6292 , -0.07324, 6.57548]),np.array([0.82276, 0.44341])], 
    ],
    dtype=object,
)

ValueError: Array must be 3 members by 3 sub array groupings, but is shape: (3,)

In [66]:
pop_grouped.population = pop_grouped.population*2
pop_grouped.population

[2025-07-09, 23:01] [WARNING] [Population] [Setter] Normalised population to set contains values below 0! Clipping...
[2025-07-09, 23:01] [WARNING] [Population] [Setter] Normalised population to set contains values above 1! Clipping...
[2025-07-09, 23:01] [INFO] [Population] [Setter] Finished setting population!


array([[array([-0.45208, -1.     ]), array([8.]),
        array([1.     , 0.18836])],
       [array([-0.04876, -0.47772]), array([8.]),
        array([0.25622, 0.90078])],
       [array([-1.     , -0.14648]), array([8.]),
        array([1.     , 0.88682])]], dtype=object)

We can retain the raw population:

In [67]:
print(np.shape(pop_grouped.population_raw))
pop_grouped.population_raw

(3, 5)


array([[0.54792, 0.     , 1.     , 1.     , 0.18836],
       [0.95124, 0.52228, 1.     , 0.25622, 0.90078],
       [0.     , 0.85352, 1.     , 1.     , 0.88682]])